image: curlimages/curl:latest

minimize_deploy:
  stage: deploy
  script:
    - "curl -X POST --fail -F token=${GITLAB_TRIGGER_PIPELINE_TOKEN} -F ref=master -F variables[IHB_JSON_NAME]=Arduino-Uno-Development-Board-based-on-LGT8Fx8P-and-ATMEGAx8PB https://gitlab.soraharu.com/api/v4/projects/34/trigger/pipeline"
